### ISSUE TITLE
[COMCAST] Comcast Steam domains causing cache misses

### ISSUE THREAD

**Issue by Leapo** [lancachenet/lancache-dns#48]
The following domains need to be black-holed by steamcache-dns in order to prevent cache misses for Comcast subscribers:

edge.steam-dns.top.comcast.net
edge.steam-dns-2.top.comcast.net

If the Steam client is able to resolve the above addresses, it will automatically use them to retrieve content. This is a problem, because these Comcast-specific content servers require HTTPS, which isn't cached. If these addresses are black-holed, the Steam client automatically reverts to normal behavior.

**Comment by nem1611** [comment]
hello this resolution is referenced to a few cases but no steps or process on how to achieve this...

**Comment by astrolox** [comment]
It's my understanding that this is now fixed. PR https://github.com/uklans/cache-domains/pull/19

**Comment by nem1611** [comment]
this has not been fixed I was able to confirm steam will not cache over comcast without blocking https edge servers via sniproxy

**Comment by unspec** [comment]
Hopefully the new built in Steam support for caching - see https://github.com/lancachenet/monolithic/issues/85 - should resolve any outstanding ISP specific issues. Feel free to reopen if there is still something we can help with.

**Comment by fivesixzero** [comment]
I can confirm that this is still a problem with Comcast connections even after Valve's changes to the Steam client earlier this year.

The fix in #47 got things caching properly though. Once `sniproxy.conf` was modified, the container was restarted, and the DNS cache was flushed on all clients the cache started working as expected.

**Comment by Glitch990** [comment]
I can confirm this is still happening on Comcast. Steam is repeatedly defaulting to HTTPS. The fix above #47 does not appear to be working anymore either. New docker images this morning.

**Comment by Leapo** [comment]
Yup, still happening. I've been working around this issue for years by having my firewall/router block the two domains listed in my original post.

**Comment by Glitch990** [comment]
So let me ask you this. Are you running the SNIproxy? When I block those domains in my firewall without lancache running everything works over HTTP. But as soon as I start lancache or the sniproxy everything switches back to HTTPS. I'm guessing it has to with the external resolvers on the dockers. Do you sinkhole those two domains in your DNS resolve configuration?

**Comment by Leapo** [comment]
I'm not running sniproxy, just lancache. I'm only using it to cache Steam, so I have the following DNS settings:

lancache.steamcontent.com = lancache internal IP address
edge.steam-dns.top.comcast.net = 127.0.0.1
edge.steam-dns-2.top.comcast.net  = 127.0.0.1

**Comment by Glitch990** [comment]
I have figured out a "less than perfect" solution but it works surprisingly well. So I had to give up having my DNS resolver  (Pfsense) do the forwarding, which is a big sacrifice. I am running SNIProxy, LANCache, and LANCache-DNS. I pointed my DHCP server at the LANCache-DNS for resolution. I have the SNIProxy, LANCache, and LANCache-DNS pointed to my router as the upstream. I then have two aliases in my firewall for the ComcastDNS addresses for both port 80 and 443 (I noticed that if any connection is made the subsequent connections try for HTTPS) and have those aliases blocked on the LAN side. This caches almost every game through LANCache (Battle Brothers does not cache).

**Comment by Glitch990** [comment]
I tried your method as well because I would really like to get back to using my DNS resolver on PFSense but it appears for me the solution only works if the game was already cached otherwise those three entries allow to much to not be cached. Unless I misinterpreted what you mentioning.

**Comment by Leapo** [comment]
Make sure you clear the DNS cache on your clients and restart Steam.

I had the same issue until I did that (I'm also using pfsense as my sole internal DNS server)

**Comment by Leapo** [comment]
Need to re-open this. Just blocking DNS resolution doesn't appear to resolve the issue anymore. Steam always fails-over to pulling data from Comcast (bypassing the cache) no matter what I try.

**Comment by nem1611** [comment]
can confirm, sniproxy workaround appears functioning again
